version = 1

# Moving these to the top makes them global
test_patterns = [
  "Tests/**"
]

exclude_patterns = [
  ".build/**",
  "**/.swiftpm/**",
  "**/DerivedData/**"
]

[[analyzers]]
name = "swift"
enabled = true
skip_rules = ["SW-W1001"] # Default parameters should always be positioned at the end

[[analyzers]]
name = "secrets"
enabled = true
